name: dart_simdjson
description: Demo of using simdjson for parsing JSON from bytes.
version: 0.0.1
repository: https://github.com/mraleph/dart_simdjson
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ^6.8.0
  build: ^2.4.1
  ffi: any
  source_gen: ^1.5.0

dev_dependencies:
  build_runner: ^2.4.12
  ffigen: ^13.0.0
  lints: ^4.0.0
  logging: ^1.2.0
  native_assets_cli: ^0.7.2
  native_toolchain_c: ^0.5.2
  test: ^1.24.0
